# This workflow package and publish a Helm chart to Google Artifact Registry
# when a commit is pushed to the "main" branch.
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Authenticate Docker to Artifact Registry
# 3. Package the Helm chart
# 4. Publish it to Google Artifact Registry

name: Package and Publish Helm Chart

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: "" # TODO: Set your project ID
  GAR_LOCATION: "" # TODO: Set your Artifact Registry location
  REPOSITORY: "" # TODO: Set your Artifact Registry repository
  CHART: "" # TODO: Set your Helm chart name

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          # https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}" # e.g. - "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}" # e.g. - "my-service-account@my-project.iam.gserviceaccount.com"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Package Helm Chart
        run: |-
          helm package ./helm/${{ env.CHART }}

      - name: Publish Helm Chart
        run: |-
          helm push ${{ env.CHART }}-*.tgz oci://${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}
