apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: webapp
spec:
  selector:
    app: webapp
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
